<template><div><h1 id="the-faq-s-section" tabindex="-1"><a class="header-anchor" href="#the-faq-s-section"><span>The FAQ's Section</span></a></h1>
<h2 id="q-how-do-i-install-the-toho-c-mod" tabindex="-1"><a class="header-anchor" href="#q-how-do-i-install-the-toho-c-mod"><span><font color=cyan>Q: How do I install the TOHO-C mod?</font></span></a></h2>
<p>A: You don’t need to install anything for the TOHO-C mod if you’re a player. Since it’s a host-only mod, as long as the host has it enabled, everyone can enjoy the new content without having to download anything.</p>
<h2 id="q-what-does-toho-c-stand-for-and-what-s-different-about-this-mod" tabindex="-1"><a class="header-anchor" href="#q-what-does-toho-c-stand-for-and-what-s-different-about-this-mod"><span><font color=purple>Q: What does TOHO-C stand for, and what’s different about this mod?</font></span></a></h2>
<p>A: TOHO-C stands for Touhou Crew, a mod inspired by the Touhou Project series. It adds new characters, abilities, and mechanics themed around the series, making the gameplay more exciting and unpredictable while keeping the core Among Us experience intact.</p>
<h2 id="q-do-players-need-to-install-the-mod-too-or-only-the-host" tabindex="-1"><a class="header-anchor" href="#q-do-players-need-to-install-the-mod-too-or-only-the-host"><span><font color=red>Q: Do players need to install the mod too, or only the host?</font></span></a></h2>
<p>A: Only the host needs to have the mod installed. As long as the host is running TOHO-C, everyone in the lobby will be able to experience the new features automatically.</p>
<h2 id="q-what-new-roles-or-abilities-does-the-toho-c-mod-add" tabindex="-1"><a class="header-anchor" href="#q-what-new-roles-or-abilities-does-the-toho-c-mod-add"><span><font color=lime>Q: What new roles or abilities does the TOHO-C mod add?</font></span></a></h2>
<p>A: TOHO-C introduces several new roles inspired by the Touhou Project, each with unique abilities. For example, you might find a role that can manipulate time or cast spells to sabotage or protect crewmates. There are also new impostor tricks and ways for crewmates to defend themselves.</p>
<h2 id="q-how-does-the-mod-change-standard-tasks-or-rules" tabindex="-1"><a class="header-anchor" href="#q-how-does-the-mod-change-standard-tasks-or-rules"><span><font color=blue>Q: How does the mod change standard tasks or rules?</font></span></a></h2>
<p>A: While the basic tasks remain similar, TOHO-C tweaks certain rules to fit the Touhou theme. Some tasks might have additional steps, or new elements may be added to increase difficulty. You'll also notice special abilities that can impact how tasks are completed or how sabotage works.</p>
<h2 id="q-are-there-any-new-visual-or-sound-effects-unique-to-this-mod" tabindex="-1"><a class="header-anchor" href="#q-are-there-any-new-visual-or-sound-effects-unique-to-this-mod"><span><font color=pink>Q: Are there any new visual or sound effects unique to this mod?</font></span></a></h2>
<p>A: Yes! TOHO-C comes with some custom visuals and sound effects that bring the Touhou Project atmosphere into the game. From spell circles to special background music, you’ll notice a distinct flair compared to standard Among Us.</p>
<h2 id="q-does-the-mod-change-the-number-of-imposters-or-crew-size" tabindex="-1"><a class="header-anchor" href="#q-does-the-mod-change-the-number-of-imposters-or-crew-size"><span><font color=yellow>Q: Does the mod change the number of imposters or crew size?</font></span></a></h2>
<p>A: The number of imposters and crew size can be adjusted like normal, but the mod allows for more flexibility in role assignments and game balance. Some roles from TOHO-C might tilt the odds in favor of either side depending on how they’re used.</p>
<h2 id="q-are-there-any-specific-settings-the-host-needs-to-enable-for-toho-c" tabindex="-1"><a class="header-anchor" href="#q-are-there-any-specific-settings-the-host-needs-to-enable-for-toho-c"><span><font color=amber>Q: Are there any specific settings the host needs to enable for TOHO-C?</font></span></a></h2>
<p>A: The mod has a few custom settings to enhance the TOHO experience. Make sure to review the mod settings menu before starting the game, where you can adjust role distributions and enable specific abilities that fit your lobby’s playstyle.</p>
<h2 id="q-is-this-mod-compatible-with-other-mods-or-standard-among-us-updates" tabindex="-1"><a class="header-anchor" href="#q-is-this-mod-compatible-with-other-mods-or-standard-among-us-updates"><span><font color=gray>Q: Is this mod compatible with other mods or standard Among Us updates?</font></span></a></h2>
<p>A: TOHO-C is designed to work with the base game, but it may not be compatible with other mods that alter game mechanics. After Among Us updates, the mod might need a quick patch, so keep an eye on updates to ensure everything runs smoothly.</p>
<h2 id="q-does-toho-c-affect-the-map-layout-or-add-new-maps" tabindex="-1"><a class="header-anchor" href="#q-does-toho-c-affect-the-map-layout-or-add-new-maps"><span><font color=#008b8b>Q: Does TOHO-C affect the map layout or add new maps?</font></span></a></h2>
<p>A: TOHO-C doesn’t introduce any new maps but modifies certain interactions within existing ones. You may notice new ways to use the environment based on the abilities of different roles, adding more depth to the maps you already know.</p>
</div></template>


